# kuusi
# Copyright (C) 2014-2024  Christoph MÃ¼ller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generic assignments without a distro-specific scope

# Distros pecific matches

# Debian
[assignment.graphical-installer-allows-selection-of-many-packages]
from = ["many-choices-gui"]
to = ["debian"]
how = "positive"

# For Ubuntu, the installation process for desktop editions is implemented using a GUI setup. This setup gives basic options (such as hostname etc), but has a predefined selection of software to be installed.


