# distrochooser
# Copyright (C) 2014-2026 Christoph MÃ¼ller <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# distrochooser::translation::en::I often need help from others to fix problems with my computer
# distrochooser::translation::key::beginner-usage-description
[facette.beginner-usage]
topic = "pc-knowledge"

# distrochooser::translation::en::I am already able to solve some computer problems by myself
# distrochooser::translation::key::advanced-usage-description
[facette.advanced-usage]
topic = "pc-knowledge"

# distrochooser::translation::en::I can troubleshoot most or all computer problems by myself
# distrochooser::translation::key::professional-usage-description
[facette.professional-usage]
topic = "pc-knowledge"
