# distrochooser
# Copyright (C) 2014-2026 Christoph MÃ¼ller <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.



# distrochooser::translation::en::Ubuntu is a Linux distribution built by the company Canonical
# distrochooser::translation::key::ubuntu-description
[choosable.ubuntu]
bg_color = "#E95420"
fg_color = "#FFFFFF"
name = "Ubuntu"

[[meta]]
choosable="ubuntu"
meta_name = "website"
meta_value = "https://ubuntu.com"


[[meta]]
choosable="ubuntu"
meta_name = "age"
meta_value = "2004-10-20"


[[meta]]
choosable="ubuntu"
meta_name = "country"
meta_value = "gb"


[[meta]]
choosable="ubuntu"
meta_name = "languages"
meta_value = "en"


# distrochooser::translation::en::Debian is a Linux distribution with high focus on stability
# distrochooser::translation::key::debian-description
[choosable.debian]
name = "Debian"
bg_color = "#d70a53"
fg_color = "white"

[[meta]]
choosable="debian"
meta_name = "website"
meta_value = "https://debian.org"

[[meta]]
choosable="debian"
meta_name = "age"
meta_value = "1993-09-15"

[[meta]]
choosable="debian"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="debian"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Anonymization is the main focus of Tails, which can be used from USB or optical discs
# distrochooser::translation::key::tails-description
[choosable.tails]
name = "Tails"
bg_color = "#56347c"
fg_color = "white"

[[meta]]
choosable="tails"
meta_name = "website"
meta_value = "https://tails.boum.org/"

[[meta]]
choosable="tails"
meta_name = "age"
meta_value = "2009-06-23"

[[meta]]
choosable="tails"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="tails"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Devuan is a Debian clone without usage of the systemd toolkit
# distrochooser::translation::key::devuan-description
[choosable.devuan]
bg_color = "#E5EDB0"
fg_color = "#662984"
name = "Devuan"

[[meta]]
choosable="devuan"
meta_name = "website"
meta_value = "https://devuan.org/"

[[meta]]
choosable="devuan"
meta_name = "age"
meta_value = "2016-05-03"

[[meta]]
choosable="devuan"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Arch is a rolling release Linux distribution based on the KISS principle
# distrochooser::translation::key::arch-description
[choosable.arch]
name = "Arch"
bg_color = "#08c"
fg_color = "white"

[[meta]]
choosable="arch"
meta_name = "website"
meta_value = "https://www.archlinux.org/"

[[meta]]
choosable="arch"
meta_name = "age"
meta_value = "2002-03-11"

[[meta]]
choosable="arch"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Linux Mint is a Ubuntu based Linux distribution with pre-installed proprietary components, such as multimedia codecs.
# distrochooser::translation::key::mint-description
[choosable.mint]
name = "Linux Mint"
bg_color = "#a4e265"
fg_color = "white"

[[meta]]
choosable="mint"
meta_name = "website"
meta_value = "https://www.linuxmint.com/"

[[meta]]
choosable="mint"
meta_name = "age"
meta_value = "2006-08-27"

[[meta]]
choosable="mint"
meta_name = "country"
meta_value = "fr"

[[meta]]
choosable="mint"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::openSUSE aims to deliver a stable and user-friendly Linux distribution, mostly for end users
# distrochooser::translation::key::opensuse-description
[choosable.opensuse]
name = "openSUSE"
bg_color = "#173f4f"
fg_color = "#35b9ab"

[[meta]]
choosable="opensuse"
meta_name = "website"
meta_value = "https://www.opensuse.org/"

[[meta]]
choosable="opensuse"
meta_name = "age"
meta_value = "1993-03-01"

[[meta]]
choosable="opensuse"
meta_name = "country"
meta_value = "lu"

[[meta]]
choosable="opensuse"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Solus OS is a rolling release Linux distribution which started as a Chrome OS clone
# distrochooser::translation::key::solus-description
[choosable.solus]
name = "Solus OS"
bg_color = "#5294E2"
fg_color = "white"

[[meta]]
choosable="solus"
meta_name = "website"
meta_value = "https://getsol.us/home/"

[[meta]]
choosable="solus"
meta_name = "age"
meta_value = "2015-12-27"

[[meta]]
choosable="solus"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Manjaro is a rolling release Linux distribution focused on user friendliness
# distrochooser::translation::key::manjaro-description
[choosable.manjaro]
name = "Manjaro"
bg_color = "#34be5b"
fg_color = "white"

[[meta]]
choosable="manjaro"
meta_name = "website"
meta_value = "https://manjaro.org"

[[meta]]
choosable="manjaro"
meta_name = "age"
meta_value = "2011-06-11"

[[meta]]
choosable="manjaro"
meta_name = "country"
meta_value = "de"

[[meta]]
choosable="manjaro"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::PCLinuxOS is a Mandrake-based Linux distribution focused on a user-friendly interface.
# distrochooser::translation::key::pclinuxos-description
[choosable.pclinuxos]
name = "PCLinuxOS"
bg_color = "black"
fg_color = "white"

[[meta]]
choosable="pclinuxos"
meta_name = "website"
meta_value = "http://www.pclinuxos.com/"

[[meta]]
choosable="pclinuxos"
meta_name = "age"
meta_value = "2003-10-24"

[[meta]]
choosable="pclinuxos"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="pclinuxos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Rocky Linux is a open source Linux distribution targeted to be 100% compatible with Red Hat Enterprise Linux (RHEL)
# distrochooser::translation::key::rocky-description
[choosable.rocky]
name = "Rocky Linux"
bg_color = "#10b981"
fg_color = "white"

[[meta]]
choosable="rocky"
meta_name = "website"
meta_value = "https://rockylinux.org/"

[[meta]]
choosable="rocky"
meta_name = "age"
meta_value = "2021-03-01"

[[meta]]
choosable="rocky"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="rocky"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Red Hat Enterprise Linux (RHEL) is a enterprise and stability focused Linux distribution
# distrochooser::translation::key::rhel-description
[choosable.rhel]
name = "Red Hat Enterprise Linux (RHEL)"
bg_color = "#cf0000"
fg_color = "white"

[[meta]]
choosable="rhel"
meta_name = "website"
meta_value = "https://www.redhat.com/de/technologies/linux-platforms/enterprise-linux"

[[meta]]
choosable="rhel"
meta_name = "age"
meta_value = "2000-02-22"

[[meta]]
choosable="rhel"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="rhel"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::MX Linux is a middleweight resource usage Linux distribution with focus on a efficient and elegant daily usage.
# distrochooser::translation::key::mxlinux-description
[choosable.mxlinux]
name = "MX Linux"
bg_color = "#134452"
fg_color = "white"

[[meta]]
choosable="mxlinux"
meta_name = "website"
meta_value = "https://mxlinux.org/"

[[meta]]
choosable="mxlinux"
meta_name = "age"
meta_value = "2003-11-04"

[[meta]]
choosable="mxlinux"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Fedora is a Red Hat backed Linux distribution with a large focus on free software
# distrochooser::translation::key::fedora-description
[choosable.fedora]
name = "Fedora"
bg_color = "#3c6eb4"
fg_color = "white"

[[meta]]
choosable="fedora"
meta_name = "website"
meta_value = "https://getfedora.org/"

[[meta]]
choosable="fedora"
meta_name = "age"
meta_value = "2014-03-24"

[[meta]]
choosable="fedora"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="fedora"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Gentoo is a flexible Linux distribution for advanced users
# distrochooser::translation::key::gentoo-description
[choosable.gentoo]
name = "Gentoo"
bg_color = "#4d4270"
fg_color = "white"

[[meta]]
choosable="gentoo"
meta_name = "website"
meta_value = "https://www.gentoo.org/"

[[meta]]
choosable="gentoo"
meta_name = "age"
meta_value = "2002-03-31"

[[meta]]
choosable="gentoo"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="gentoo"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Knoppix is a live-mode focused operating system with a wide range of hardware support
# distrochooser::translation::key::knoppix-description
[choosable.knoppix]
name = "Knoppix"
bg_color = "#dddddd"
fg_color = "blue"

[[meta]]
choosable="knoppix"
meta_name = "website"
meta_value = "http://www.knoppix.org/"

[[meta]]
choosable="knoppix"
meta_name = "age"
meta_value = "2000-09-30"

[[meta]]
choosable="knoppix"
meta_name = "country"
meta_value = "de"

[[meta]]
choosable="knoppix"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Crux Linux is a lightweight 64 bit focused operating system with recent tools and libraries
# distrochooser::translation::key::cruxlinux-description
[choosable.cruxlinux]
name = "Crux Linux"
bg_color = "#dfeeee"
fg_color = "black"

[[meta]]
choosable="cruxlinux"
meta_name = "website"
meta_value = "https://crux.nu/"

[[meta]]
choosable="cruxlinux"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Zorin OS is a beginner focused Linux distribution with a windows-like user interface
# distrochooser::translation::key::zorinos-description
[choosable.zorinos]
name = "Zorin OS"
bg_color = "#15a6f0"
fg_color = "white"

[[meta]]
choosable="zorinos"
meta_name = "website"
meta_value = "https://zorin.com/os/"

[[meta]]
choosable="zorinos"
meta_name = "age"
meta_value = "2009-01-01"

[[meta]]
choosable="zorinos"
meta_name = "country"
meta_value = "ie"

[[meta]]
choosable="zorinos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::elementary OS is a Ubuntu-based Linux distribution, focused on an elegant and fast user experience
# distrochooser::translation::key::elementaryos-description
[choosable.elementaryos]
name = "elementary OS"
bg_color = "#555761"
fg_color = "white"

[[meta]]
choosable="elementaryos"
meta_name = "website"
meta_value = "https://elementary.io/"

[[meta]]
choosable="elementaryos"
meta_name = "age"
meta_value = "2011-03-31"

[[meta]]
choosable="elementaryos"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="elementaryos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Qubes OS executes processes in virtual machines in favor of security
# distrochooser::translation::key::qubesos-description
[choosable.qubesos]
name = "Qubes OS"
bg_color = "#f5f5f5"
fg_color = "black"

[[meta]]
choosable="qubesos"
meta_name = "website"
meta_value = "https://www.qubes-os.org/"

[[meta]]
choosable="qubesos"
meta_name = "age"
meta_value = "2012-09-03"

[[meta]]
choosable="qubesos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::NixOS uses the Nix package manager. It uses declarative configuration and allows reliable system upgrades.
# distrochooser::translation::key::nixos-description
[choosable.nixos]
name = "NixOS"
bg_color = "None"
fg_color = "None"

[[meta]]
choosable="nixos"
meta_name = "website"
meta_value = "None"

[[meta]]
choosable="nixos"
meta_name = "age"
meta_value = "2003-06-03"

[[meta]]
choosable="nixos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Xubuntu is an Ubuntu-based Linux distribution powered by the lightweight XFCE desktop environment
# distrochooser::translation::key::xubuntu-description
[choosable.xubuntu]
name = "Xubuntu"
bg_color = "#0c72b7"
fg_color = "white"

[[meta]]
choosable="xubuntu"
meta_name = "website"
meta_value = "https://xubuntu.org/"

[[meta]]
choosable="xubuntu"
meta_name = "age"
meta_value = "2006-06-23"

[[meta]]
choosable="xubuntu"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Lubuntu is an Ubuntu-based Linux distribution powered by the lightweight LXQt desktop environment
# distrochooser::translation::key::lubuntu-description
[choosable.lubuntu]
name = "Lubuntu"
bg_color = "#3e2e53"
fg_color = "white"

[[meta]]
choosable="lubuntu"
meta_name = "website"
meta_value = "https://lubuntu.me/"

[[meta]]
choosable="lubuntu"
meta_name = "age"
meta_value = "2008-10-01"

[[meta]]
choosable="lubuntu"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Ubuntu MATE is an Ubuntu-based Linux distribution powered by the lightweight MATE desktop environment
# distrochooser::translation::key::ubuntumate-description
[choosable.ubuntumate]
name = "Ubuntu MATE"
bg_color = "#87a556"
fg_color = "white"

[[meta]]
choosable="ubuntumate"
meta_name = "website"
meta_value = "https://ubuntu-mate.org/"

[[meta]]
choosable="ubuntumate"
meta_name = "age"
meta_value = "2014-10-23"

[[meta]]
choosable="ubuntumate"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Void Linux is a rolling release Linux distribution without systemd
# distrochooser::translation::key::void-description
[choosable.void]
name = "Void Linux"
bg_color = "#478061"
fg_color = "white"

[[meta]]
choosable="void"
meta_name = "website"
meta_value = "https://voidlinux.org/"

[[meta]]
choosable="void"
meta_name = "age"
meta_value = "2008-01-01"

[[meta]]
choosable="void"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Artix is an Arch Linux based Linux distribution which can use several init systems besides systemd, for example OpenRC
# distrochooser::translation::key::artix-description
[choosable.artix]
name = "Artix"
bg_color = "black"
fg_color = "#8bf"

[[meta]]
choosable="artix"
meta_name = "website"
meta_value = "https://artixlinux.org/"

[[meta]]
choosable="artix"
meta_name = "age"
meta_value = "2017-01-01"

[[meta]]
choosable="artix"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Kubuntu is an Ubuntu-based Linux distribution with a pre-installed KDE as a desktop
# distrochooser::translation::key::kubuntu-description
[choosable.kubuntu]
name = "Kubuntu"
bg_color = "#0079C1"
fg_color = "white"

[[meta]]
choosable="kubuntu"
meta_name = "website"
meta_value = "https://kubuntu.org/"

[[meta]]
choosable="kubuntu"
meta_name = "age"
meta_value = "2005-04-08"

[[meta]]
choosable="kubuntu"
meta_name = "country"
meta_value = "us,de"

[[meta]]
choosable="kubuntu"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Pop!_OS is an Ubuntu-based Linux distribution powered by the GNOME desktop environment customized from System76
# distrochooser::translation::key::popos-description
[choosable.popos]
name = "Pop!_OS"
bg_color = "#48b9c7"
fg_color = "white"

[[meta]]
choosable="popos"
meta_name = "website"
meta_value = "https://pop.system76.com/"

[[meta]]
choosable="popos"
meta_name = "age"
meta_value = "2017-10-27"

[[meta]]
choosable="popos"
meta_name = "country"
meta_value = "us"

[[meta]]
choosable="popos"
meta_name = "languages"
meta_value = "en"

# distrochooser::translation::en::Deepin is a chinese, Debian based Linux distribution offering an own desktop called Deepin Desktop Environment.
# distrochooser::translation::key::deepin-description
[choosable.deepin]
name = "Deepin"
bg_color = "#2fc6ff"
fg_color = "white"

[[meta]]
choosable="deepin"
meta_name = "website"
meta_value = "https://www.deepin.org/en/"

[[meta]]
choosable="deepin"
meta_name = "age"
meta_value = "2004-02-28"

[[meta]]
choosable="deepin"
meta_name = "country"
meta_value = "cn"

[[meta]]
choosable="deepin"
meta_name = "languages"
meta_value = "en"
